2020-07-30 18:49:15,857 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 28, in get_or_NoFound
    abort(400, code=1,data="",err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 18:50:33,767 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 28, in get_or_NoFound
    abort(400, code=1,data="",err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 18:50:48,136 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 28, in get_or_NoFound
    abort(400, code=1,data="",err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 18:51:20,162 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 29, in get_or_NoFound
    abort(400, code=1,data="",err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 18:51:46,803 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 29, in get_or_NoFound
    abort(400, code=1,data="",err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 18:52:03,287 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - __call__() got multiple values for argument 'code'
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 29, in get_or_NoFound
    abort(400, code=1,data="",err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
TypeError: __call__() got multiple values for argument 'code'
2020-07-30 18:53:01,197 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 27, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 18:53:31,692 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 28, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 18:57:07,469 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.query.get_or_404(projectId,"hah")
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 24, in get_or_404
    abort(404, description=description)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2020-07-30 18:58:16,084 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_404(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 25, in get_or_404
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 18:58:19,417 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_404(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 28, in get_or_404
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:01:25,577 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 38, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:02:54,902 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 38, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:03:28,249 - App.Api.envOpt - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/envOpt.py", line 89, in delete
    e = Envs.get(id)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 38, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:04:18,711 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 38, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:05:00,744 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 38, in get_or_NoFound
    abort(404, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2020-07-30 19:05:15,611 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - no exception for 10000
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 38, in get_or_NoFound
    abort(10000, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 806, in __call__
    raise LookupError("no exception for %r" % code)
LookupError: no exception for 10000
2020-07-30 19:05:29,087 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 38, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:05:46,030 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 38, in get_or_NoFound
    abort(400, code=1, data="s", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:07:21,549 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 28, in get_or_NoFound
    abort(400, code=1, data="", err="projectId 不存在或删除")
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:07:42,792 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    Project.assertIdExisted(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 139, in assertIdExisted
    abort(400, code=1, data="", err="projectId 不存在或删除")
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:12:48,758 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 29, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:13:16,555 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 29, in get_or_NoFound
    abort(400)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:13:42,971 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 30, in get_or_NoFound
    abort(400, **dict(code=1, data="", err=err_msg))
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:13:55,899 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - __call__() got multiple values for argument 'code'
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 30, in get_or_NoFound
    abort(400, **dict(code=1, data="", err=err_msg))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
TypeError: __call__() got multiple values for argument 'code'
2020-07-30 19:14:14,501 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: {'code': 1, 'data': '', 'err': 'id已刪除'}
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 30, in get_or_NoFound
    abort(400, dict(code=1, data="", err=err_msg))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: {'code': 1, 'data': '', 'err': 'id已刪除'}
2020-07-30 19:14:26,553 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - __call__() got multiple values for argument 'code'
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 30, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
TypeError: __call__() got multiple values for argument 'code'
2020-07-30 19:14:33,896 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - __call__() got multiple values for argument 'code'
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 30, in get_or_NoFound
    abort(400, **dict(code=1, data="", err=err_msg))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
TypeError: __call__() got multiple values for argument 'code'
2020-07-30 19:14:40,985 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: {'code': 1, 'data': '', 'err': 'id已刪除'}
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 30, in get_or_NoFound
    abort(400, dict(code=1, data="", err=err_msg))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: {'code': 1, 'data': '', 'err': 'id已刪除'}
2020-07-30 19:15:45,166 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 'tuple' object has no attribute 'delete'
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 95, in delete
    p.delete()
AttributeError: 'tuple' object has no attribute 'delete'
2020-07-30 19:17:02,673 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: <Response 41 bytes [200 OK]>
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 30, in get_or_NoFound
    abort(400, jsonify(dict(code=1, data="", err=err_msg)))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: <Response 41 bytes [200 OK]>
2020-07-30 19:17:34,839 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - abort() argument after ** must be a mapping, not Response
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400, **jsonify(dict(code=1, data="", err=err_msg)))
TypeError: abort() argument after ** must be a mapping, not Response
2020-07-30 19:18:10,988 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:19:09,028 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - ??? Unknown Error: None
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 32, in get_or_NoFound
    abort(res)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 804, in __call__
    raise HTTPException(response=code)
werkzeug.exceptions.HTTPException: ??? Unknown Error: None
2020-07-30 19:19:20,395 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - ??? Unknown Error: None
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 33, in get_or_NoFound
    abort(res)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 804, in __call__
    raise HTTPException(response=code)
werkzeug.exceptions.HTTPException: ??? Unknown Error: None
2020-07-30 19:21:07,389 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:27:38,764 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - __call__() got multiple values for argument 'code'
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400, code=1, data="", err=err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
TypeError: __call__() got multiple values for argument 'code'
2020-07-30 19:28:00,112 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:28:14,128 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: {'err': 'dfs'}
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400,{"err":"dfs"})
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: {'err': 'dfs'}
2020-07-30 19:29:02,874 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - ??? Unknown Error: None
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort({"err":"fsdf"})
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 804, in __call__
    raise HTTPException(response=code)
werkzeug.exceptions.HTTPException: ??? Unknown Error: None
2020-07-30 19:29:13,986 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - abort() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400,{"err":"fsdf"})
TypeError: abort() takes 1 positional argument but 2 were given
2020-07-30 19:29:32,080 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400,hell="fdsf")
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:29:52,695 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400,err="ferr")
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:30:40,066 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400,err="ferr")
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:32:47,381 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400,)
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:35:16,161 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - ??? Unknown Error: None
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(make_response(jsonify(message="Message goes here"), 400))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 804, in __call__
    raise HTTPException(response=code)
werkzeug.exceptions.HTTPException: ??? Unknown Error: None
2020-07-30 19:35:55,500 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - ??? Unknown Error: None
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(make_response(jsonify(message="Message goes here"), 400))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 804, in __call__
    raise HTTPException(response=code)
werkzeug.exceptions.HTTPException: ??? Unknown Error: None
2020-07-30 19:37:03,266 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: <Response 32 bytes [200 OK]>
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400,make_response(jsonify(message="Message goes here")))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: <Response 32 bytes [200 OK]>
2020-07-30 19:37:57,529 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT project.id AS project_id, project.create_time AS project_create_time, project.update_time AS project_update_time, project.status AS project_status, project.project_name AS project_project_name, project.project_desc AS project_project_desc 
FROM project 
WHERE project.id = ?]
[parameters: (<class 'App.Api.projectOpt.ProjectOpt'>,)]
(Background on this error at: http://sqlalche.me/e/rvf5)
Traceback (most recent call last):
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    Project.assertIdExisted(ProjectOpt)
  File "/home/mi/Fan_Platform/Model/Models.py", line 138, in assertIdExisted
    p = cls.query.get(id)
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1004, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1119, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 284, in load_on_pk_identity
    return q.one()
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3358, in one
    ret = self.one_or_none()
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3327, in one_or_none
    ret = list(self)
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3403, in __iter__
    return self._execute_and_instances(context)
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3428, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/mi/flask/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT project.id AS project_id, project.create_time AS project_create_time, project.update_time AS project_update_time, project.status AS project_status, project.project_name AS project_project_name, project.project_desc AS project_project_desc 
FROM project 
WHERE project.id = ?]
[parameters: (<class 'App.Api.projectOpt.ProjectOpt'>,)]
(Background on this error at: http://sqlalche.me/e/rvf5)
2020-07-30 19:38:21,846 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    Project.assertIdExisted(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 140, in assertIdExisted
    abort(400, code=1, data="", err="projectId 不存在或删除")
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2020-07-30 19:39:37,886 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - ??? Unknown Error: None
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(jsonify(message="Message goes here"))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 804, in __call__
    raise HTTPException(response=code)
werkzeug.exceptions.HTTPException: ??? Unknown Error: None
2020-07-30 19:39:45,061 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - name 'jsonify' is not defined
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(jsonify(message="Message goes here"))
NameError: name 'jsonify' is not defined
2020-07-30 19:39:57,972 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - ??? Unknown Error: None
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(jsonify(message="Message goes here"))
  File "/home/mi/flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 804, in __call__
    raise HTTPException(response=code)
werkzeug.exceptions.HTTPException: ??? Unknown Error: None
2020-07-30 19:40:15,178 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - ??? Unknown Error: None
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(jsonify(message="Message goes here"))
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 804, in __call__
    raise HTTPException(response=code)
werkzeug.exceptions.HTTPException: ??? Unknown Error: None
2020-07-30 19:41:34,018 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: err
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400,'err')
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: err
2020-07-30 19:41:59,720 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: id已删除
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400, err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: id已删除
2020-07-30 19:45:04,505 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: id已删除
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 35, in get
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400, err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: id已删除
2020-07-30 19:47:20,848 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: id已删除
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 94, in delete
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 34, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400, err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: id已删除
2020-07-30 19:53:17,035 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: id已删除
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 113, in post
    p = Project.get(projectId)
  File "/home/mi/Fan_Platform/Model/Models.py", line 34, in get
    return cls.query.get_or_NoFound(id)
  File "/home/mi/Fan_Platform/comments/MyBaseQueryOpt.py", line 31, in get_or_NoFound
    abort(400, err_msg)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: id已删除
2020-07-30 20:00:07,147 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: projectId 不存在或删除
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 118, in post
    Project.assertIdExisted(i).Delete()
  File "/home/mi/Fan_Platform/Model/Models.py", line 140, in assertIdExisted
    abort(400, "projectId 不存在或删除")
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: projectId 不存在或删除
2020-07-30 20:00:27,881 - /home/mi/Fan_Platform/App/Api/projectOpt.py - ERROR - 400 Bad Request: projectId 2 不存在或删除
Traceback (most recent call last):
  File "/home/mi/Fan_Platform/App/Api/projectOpt.py", line 118, in post
    Project.assertIdExisted(i).Delete()
  File "/home/mi/Fan_Platform/Model/Models.py", line 140, in assertIdExisted
    abort(400, f"projectId {id} 不存在或删除")
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/mi/flask/lib/python3.6/site-packages/werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: projectId 2 不存在或删除
